name: Build Android App Bundle (AAB) & APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Release Keystore
        run: |
          cd android/app
          keytool -genkey -v -keystore release.keystore -alias bilingokey -keyalg RSA -keysize 2048 -validity 10000 -storepass bilingo123456 -keypass bilingo123456 -dname "CN=Bilingo, OU=Radio, O=Bilingo, L=Taipei, ST=Taiwan, C=TW"

      - name: Build Android App Bundle (AAB) & APK
        run: |
          cd android
          gradle bundleRelease assembleRelease assembleDebug

      - name: Upload Release AAB to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/*.aab

      - name: Upload Release APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/*.apk

      - name: Upload Debug APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
